variable "project" {}
variable "function_name" {}
variable "function_entry_point" {}
variable "region" {}
variable "source_dir" {}
variable "runtime" {}
variable "pubsub_name" {}
variable "env_vars" {}
variable "max-instances" {}
variable "available_memory_mb" {}